DEBUG = True
CSRF_ENABLED = True

SQLALCHEMY_DATABASE_URI = "postgres:///logbud"
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = "OOOOOOOOBBBLLKKKJHKJKJkldkjdskldsjk333k3k3"
